default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: rrtodo_dev
  username: postgres
  password: password
  port: 5433

test:
  <<: *default
  host: localhost
  database: rrtodo_test
  username: postgres
  password: password
  port: 5433

production:
  <<: *default
  database: rrtodo
  username: test1
  password: password